language: generic

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sudo sysctl -w vm.max_map_count=262144  # Increase memory mapping (if applicable)

env:
  - UV_THREADPOOL_SIZE=2  # Limit Node.js worker threads
  - NODE_OPTIONS="--max-old-space-size=4096"  # Increase memory allocation

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

after_success:
  - docker tag udagram-api-feed nmhieu981999/udagram-api-feed:v1
  - docker push nmhieu981999/udagram-api-feed:v1

  - docker tag udagram-api-user nmhieu981999/udagram-api-user:v1
  - docker push nmhieu981999/udagram-api-user:v1

  - docker tag udagram-frontend nmhieu981999/udagram-frontend:v1
  - docker push nmhieu981999/udagram-frontend:v1

  - docker tag reverseproxy nmhieu981999/reverseproxy:v1
  - docker push nmhieu981999/reverseproxy:v1
