language: generic

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

after_success:
  - docker tag udagram-api-feed sudkul/udagram-api-feed:v1
  - docker push sudkul/udagram-api-feed:v1

  - docker tag udagram-api-user sudkul/udagram-api-user:v1
  - docker push sudkul/udagram-api-user:v1

  - docker tag udagram-api-frontend sudkul/udagram-api-frontend:v1
  - docker push sudkul/udagram-api-frontend:v1

  - docker tag udagram-reverseproxy sudkul/udagram-reverseproxy:v1
  - docker push sudkul/udagram-reverseproxy:v1