apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-reserveproxy-deployment
  labels:
    app: backend-reserveproxy
spec:
  replicas: 1  # Adjust as needed for scaling
  selector:
    matchLabels:
      app: backend-reserveproxy
  template:
    metadata:
      labels:
        app: backend-reserveproxy
    spec:
      containers:
      - name: backend-reserveproxy
        image: nmhieu981999/reverseproxy:v1
        ports:
        - containerPort: 8080  # Assuming the backend API is listening on port 8080
        resources:
          requests:
            memory: "2Gi"
            cpu: "0.5"
          limits:
            memory: "4Gi"
            cpu: "1"
