apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: backend-feed  # This matches the label defined in your Deployment
  ports:
    - protocol: TCP
      port: 8100  # The port exposed inside the cluster
      targetPort: 8100  # The port on the container (backend service)
  type: ClusterIP  # Default type, only accessible within the cluster
